#pragma once
#ifndef _PLANTTYPE_H
#define _PLANTTYPE_H

constexpr int NULL_PLANT_ID = -1024;

enum class PlantType
{
	PLANT_PEASHOOTER,
	PLANT_SUNFLOWER,
	PLANT_CHERRYBOMB,
	PLANT_WALLNUT,
	PLANT_POTATOMINE,
	PLANT_SNOWPEA,
	PLANT_CHOMPER,
	PLANT_REPEATER,
	PLANT_PUFFSHROOM,
	PLANT_SUNSHROOM,
	PLANT_FUMESHROOM,
	// PLANT_GRAVEBUSTER,
	PLANT_HYPNOSHROOM,
	PLANT_SCAREDYSHROOM,
	PLANT_ICESHROOM,
	PLANT_ICEFUMESHROOM,	// 寒冰大喷菇（自创变种）；冒险解锁顺序由 AdventureProgression 奖励表决定
	PLANT_DOOMSHROOM,
	PLANT_LILYPAD,
	PLANT_SQUASH,
	PLANT_THREEPEATER,
	PLANT_TANGLEKELP,
	PLANT_JALAPENO,
	PLANT_SPIKEWEED,
	PLANT_TORCHWOOD,
	PLANT_TALLNUT,
	PLANT_SEASHROOM,
	PLANT_PLANTERN,
	PLANT_CACTUS,
	PLANT_BLOVER,
	PLANT_SPLITPEA,
	PLANT_STARFRUIT,
	PLANT_PUMPKINSHELL,
	PLANT_MAGNETSHROOM,
	PLANT_CABBAGEPULT,
	PLANT_FLOWERPOT,
	PLANT_KERNELPULT,
	PLANT_INSTANT_COFFEE,
	PLANT_GARLIC,
	PLANT_UMBRELLA,
	PLANT_MARIGOLD,
	PLANT_MELONPULT,
	PLANT_GATLINGPEA,
	PLANT_TWINSUNFLOWER,
	PLANT_GLOOMSHROOM,
	PLANT_CATTAIL,
	PLANT_WINTERMELON,
	PLANT_GOLD_MAGNET,
	PLANT_SPIKEROCK,
	PLANT_COBCANNON,
	PLANT_IMITATER,
	PLANT_EXPLODE_O_NUT,
	PLANT_GIANT_WALLNUT,
	PLANT_SPROUT,
	PLANT_LEFTPEATER,
	PLANT_ELITE_SCAREDYSHROOM,	// 精英胆小菇；追加在末尾以保持旧存档植物整数 ID
	PLANT_TOXICPEASHOOTER,	// 毒囊射手；继续追加在末尾以保持旧存档植物整数 ID
	PLANT_GROUNDINGSHROOM,	// 接地菇；5-9 奖励，追加在末尾以保持旧存档植物整数 ID
	PLANT_LIGHTNINGRODPOT,	// 避雷花盆；6-4 奖励，花盆承载层紫卡升级
	PLANT_SNOWANCHORNUT,	// 雪锚果；7-1 奖励，存活且位于真实冻土时持续整形冬季冲击
	PLANT_MELTSNOWPULT,	// 融雪投手；7-2 奖励，准确寒潮预报装填三发盐晶弹
	PLANT_FROSTMINE,	// 伏霜雷；7-4 奖励，预报校准并在实际冻土中埋伏地面目标
	PLANT_ALARMBELLFLOWER,	// 警铃草；7-6 奖励，中断本行最接近提交的一项特殊动作
	PLANT_FURNACECOREFLOWER,	// 炉芯花；7-7 奖励，温暖充能并阻止 3x3 内其他植物被建立冰像封存
	PLANT_LISTENINGGRASS,	// 听雪草；8-1 奖励，迫出本行地下敌人并封闭雪穴
	PLANT_AURORATORCHWOOD,	// 极光树桩；8-3 奖励，火炬树桩普通层紫卡升级
	PLANT_NORTHSTARFLOWER,	// 北极星花；8-2 奖励，按需开启九格极夜导航领域
	PLANT_ICEMIRRORGRASS,	// 冰镜草；8-5 奖励，逐面凝结并拦截敌方水平直射弹
	PLANT_BOUNDARYFLOWER,	// 界碑花；8-7 奖励，以可充能碎片拒绝九格内非连续敌方入场
	PLANT_DAWNLOTUS,	// 曙光莲；8-8 奖励，满能量后按当前红色极夜仪表人工点亮黎明
	PLANT_CARRYVINE, // 搬搬藤；9-1 奖励，整组瞬间搬运工具卡
	PLANT_ECHOSHROOM, // 回声菇，9-3 奖励
	PLANT_PRISMFLOWER, // 棱光花，9-5 奖励
	PLANT_AMBERLICHEN, // 琥珀地衣，9-7 奖励
	NUM_PLANT_TYPES,
};

#endif
