#pragma once
#ifndef _RESOURCE_KEYS_H
#define _RESOURCE_KEYS_H

#include <string>

// RKEY(X) 定义一个「键值 == 键名」的资源键常量，消除 IMAGE_X = "IMAGE_X" 这类重复书写：
//   RKEY(IMAGE_PEASHOOTER);  ==>  inline const std::string IMAGE_PEASHOOTER = "IMAGE_PEASHOOTER";
// 仅用于「键名 == 键值」的常量；键名 ≠ 键值的别名（如 IMAGE_APPROACHING、SOUND_THROW、
// REANIM_* 的 CamelCase、字体路径）仍显式书写，因为那一行携带了真信息。
// 用 inline 变量：跨翻译单元只构造一份（旧的 const std::string 在命名空间作用域是内部链接，
// 每个 #include 本头的 .cpp 都会各构造一整套，纯属浪费）。
#define RKEY(n) inline const std::string n = #n

namespace ResourceKeys
{
	namespace Textures
	{
		RKEY(IMAGE_KID);
		inline const std::string IMAGE_GLOWING = "IMAGE_AWARDGLOW";
		inline const std::string IMAGE_TROPHY = "IMAGE_TROPHY_HI_RES";
		RKEY(IMAGE_OPTIONS_CHECKBOX0);
		RKEY(IMAGE_OPTIONS_CHECKBOX1);
		RKEY(IMAGE_SEEDCHOOSER_BUTTON2);
		RKEY(IMAGE_SEEDCHOOSER_BUTTON2_GLOW);
		RKEY(IMAGE_ZEN_NEXTGARDEN);
		RKEY(IMAGE_OPTIONS_SLIDERKNOB2);
		RKEY(IMAGE_OPTIONS_SLIDERSLOT);
		RKEY(IMAGE_SELECTORSCREEN_ADVENTURE_BUTTON);
		RKEY(IMAGE_SELECTORSCREEN_ADVENTURE_HIGHLIGHT);
		RKEY(IMAGE_SELECTORSCREEN_ALMANAC);
		RKEY(IMAGE_SELECTORSCREEN_ALMANACHIGHLIGHT);
		RKEY(IMAGE_SELECTORSCREEN_BG);
		RKEY(IMAGE_SELECTORSCREEN_BG_CENTER);
		RKEY(IMAGE_SELECTORSCREEN_BG_LEFT);
		RKEY(IMAGE_SELECTORSCREEN_BG_RIGHT);
		RKEY(IMAGE_SELECTORSCREEN_CHALLENGES_BUTTON);
		RKEY(IMAGE_SELECTORSCREEN_CHALLENGES_HIGHLIGHT);
		// 挑战模式选择界面（GameSelectScene）——键由 Challenge_*.png 文件名自动派生
		RKEY(IMAGE_CHALLENGE_BACKGROUND);
		RKEY(IMAGE_CHALLENGE_WINDOW);
		RKEY(IMAGE_CHALLENGE_WINDOW_HIGHLIGHT);
		RKEY(IMAGE_MINIGAME_TROPHY);
		RKEY(IMAGE_ALMANAC_GROUNDDAY);
		RKEY(IMAGE_ALMANAC_GROUNDNIGHT);
		RKEY(IMAGE_ALMANAC_GROUNDPOOL);
		RKEY(IMAGE_SELECTORSCREEN_FLOWER1);
		RKEY(IMAGE_SELECTORSCREEN_FLOWER2);
		RKEY(IMAGE_SELECTORSCREEN_FLOWER3);
		RKEY(IMAGE_SELECTORSCREEN_GAME);
		RKEY(IMAGE_SELECTORSCREEN_GAME_SHADOW);
		RKEY(IMAGE_SELECTORSCREEN_HELP1);
		RKEY(IMAGE_SELECTORSCREEN_HELP2);
		RKEY(IMAGE_SELECTORSCREEN_OPTIONS1);
		RKEY(IMAGE_SELECTORSCREEN_OPTIONS2);
		RKEY(IMAGE_SELECTORSCREEN_QUIT1);
		RKEY(IMAGE_SELECTORSCREEN_QUIT2);
		RKEY(IMAGE_SELECTORSCREEN_STARTADVENTURE_BUTTON1);
		RKEY(IMAGE_SELECTORSCREEN_STARTADVENTURE_HIGHLIGHT);
		RKEY(IMAGE_SELECTORSCREEN_STORE);
		RKEY(IMAGE_SELECTORSCREEN_STOREHIGHLIGHT);
		RKEY(IMAGE_SELECTORSCREEN_SURIVAL);
		RKEY(IMAGE_SELECTORSCREEN_SURIVAL_SHADOW);
		RKEY(IMAGE_CARD_BK);
		RKEY(IMAGE_SEEDBANK_LONG);
		RKEY(IMAGE_SEEDCHOOSER_BACKGROUND);
		RKEY(IMAGE_SEEDCHOOSER_IMITATERADDON);
		RKEY(IMAGE_SEEDCHOOSER_BUTTON);
		RKEY(IMAGE_SEEDCHOOSER_BUTTON_DISABLED);
		RKEY(IMAGE_SEEDPACKETNORMAL);
		RKEY(IMAGE_SEEDPACKETVARIANTS);
		RKEY(IMAGE_BACKGROUND_DAY);
		RKEY(IMAGE_BACKGROUND_NIGHT);
		RKEY(IMAGE_BACKGROUND_POOL);
		RKEY(IMAGE_BACKGROUND_NIGHTPOOL);
		RKEY(IMAGE_BACKGROUND_ROOF);
		RKEY(IMAGE_BACKGROUND_ROOF_RAIN);
		RKEY(IMAGE_BACKGROUND_NIGHTROOF);
		RKEY(IMAGE_BACKGROUND_NIGHTROOF_RAIN);
		RKEY(IMAGE_BACKGROUND_WINTERGARDEN);
		RKEY(IMAGE_BACKGROUND_POLAR_NIGHT);
		RKEY(IMAGE_BACKGROUND_GLOOMCRYSTAL_MINE);
		RKEY(IMAGE_BACKGROUND_HOT_COLD_STORAGE);
		RKEY(IMAGE_COLD_STORAGE_ICE_HEAD);
		RKEY(IMAGE_MINE_ROCK_A);
		RKEY(IMAGE_MINE_ROCK_B);
		RKEY(IMAGE_MINE_ROCK_C);
		RKEY(IMAGE_MINE_ROCK_CRACKED);
		RKEY(IMAGE_MINE_RUBBLE);
		RKEY(IMAGE_MINE_CHUNKS);
		RKEY(IMAGE_MINE_PICKAXE);
		RKEY(IMAGE_MINE_ENTRANCE);
		RKEY(IMAGE_MINE_ROUTE_BUTTON);

		RKEY(IMAGE_SNOW_HOLE);
		RKEY(IMAGE_WINTER_FROST_OVERLAY_V2);
		RKEY(IMAGE_WINTER_FROST_FRONTIER_VARIANT_1);
		RKEY(IMAGE_WINTER_FROST_FRONTIER_VARIANT_2);
		RKEY(IMAGE_WINTER_THERMOMETER_FRAME_V1);
		RKEY(IMAGE_POOL_BASE);
		RKEY(IMAGE_POOL_BASE_NIGHT);
		RKEY(IMAGE_POOL_SHADING);
		RKEY(IMAGE_POOL_SHADING_NIGHT);
		RKEY(IMAGE_POOL_CAUSTIC_EFFECT);
		RKEY(IMAGE_BUNGEECORD);             // 蹦极僵尸从屏幕顶端延伸的绳索段
		RKEY(IMAGE_BUNGEETARGET);           // 蹦极僵尸下落前标记目标格的靶标
		RKEY(IMAGE_FOG_PART_0);		// 四大关迷雾 RGBA 分份贴图（fog.png，1 行 8 列）
		RKEY(IMAGE_FOG_PART_1);
		RKEY(IMAGE_FOG_PART_2);
		RKEY(IMAGE_FOG_PART_3);
		RKEY(IMAGE_FOG_PART_4);
		RKEY(IMAGE_FOG_PART_5);
		RKEY(IMAGE_FOG_PART_6);
		RKEY(IMAGE_FOG_PART_7);
		RKEY(IMAGE_MISTFUEL);			// 路灯花燃料“雾火”的透明掉落贴图
		RKEY(IMAGE_SHOVELBANK);
		RKEY(IMAGE_OPTIONS_MENUBACK);
		RKEY(IMAGE_BUTTONBIG);
		RKEY(IMAGE_BUTTONSMALL);
		RKEY(IMAGE_MESSAGEBOX);
		RKEY(IMAGE_DIALOG_TOPLEFT);
		RKEY(IMAGE_DIALOG_TOPMIDDLE);
		RKEY(IMAGE_DIALOG_TOPRIGHT);
		RKEY(IMAGE_DIALOG_CENTERLEFT);
		RKEY(IMAGE_DIALOG_CENTERMIDDLE);
		RKEY(IMAGE_DIALOG_CENTERRIGHT);
		RKEY(IMAGE_DIALOG_BOTTOMLEFT);
		RKEY(IMAGE_DIALOG_BOTTOMMIDDLE);
		RKEY(IMAGE_DIALOG_BOTTOMRIGHT);
		RKEY(IMAGE_DIALOG_HEADER);
		RKEY(IMAGE_OPTIONS_BACKTOGAMEBUTTON0);
		RKEY(IMAGE_OPTIONS_BACKTOGAMEBUTTON_LIGHT);
		inline const std::string IMAGE_FLAG_METER = "IMAGE_FLAGMETER_PART_0";
		inline const std::string IMAGE_FLAG_METERFULL = "IMAGE_FLAGMETER_PART_1";
		RKEY(IMAGE_FLAGMETERLEVELPROGRESS);
		inline const std::string IMAGE_FLAGMETER_PART_HEAD = "IMAGE_FLAGMETERPARTS_PART_0";
		inline const std::string IMAGE_FLAGMETER_PART_STICK = "IMAGE_FLAGMETERPARTS_PART_1";
		inline const std::string IMAGE_FLAGMETER_PART_FLAG = "IMAGE_FLAGMETERPARTS_PART_2";

		RKEY(IMAGE_SHOVEL);

		inline const std::string IMAGE_HUGE_WAVE_APPROACHING = "IMAGE_APPROACHING";

		inline const std::string IMAGE_FINAL_WAVE = "IMAGE_FINALWAVE";

		RKEY(IMAGE_PLANTSHADOW);
		RKEY(IMAGE_PLANTSHADOW2);
		RKEY(IMAGE_LILYPAD);
		RKEY(IMAGE_GOLDEN_ICE);
		RKEY(IMAGE_GOLDEN_ICE_CAP);

		RKEY(IMAGE_ZOMBIE_BACKUP_OUTERARM_UPPER_BONE);
		RKEY(IMAGE_ZOMBIE_BALLOON_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_BOBSLED_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_BOBSLED_OUTERARM_HAND);
		RKEY(IMAGE_ZOMBIE_BOBSLED_INSIDE);
		RKEY(IMAGE_ZOMBIE_BOBSLED1);
		RKEY(IMAGE_ZOMBIE_BOBSLED2);
		RKEY(IMAGE_ZOMBIE_BOBSLED3);
		RKEY(IMAGE_ZOMBIE_BOBSLED4);
		RKEY(IMAGE_ZOMBIE_BOSS_ARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_BUNGI_LEFTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_BUNGI_RIGHTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_DIGGER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_DIGGER_PICKAXE);
		RKEY(IMAGE_ZOMBIE_DIGGER_HARDHAT2);
		RKEY(IMAGE_ZOMBIE_DIGGER_HARDHAT3);
		RKEY(IMAGE_ZOMBIE_DIGGER_HARDHAT);
		RKEY(IMAGE_ZOMBIE_SNOWBURROW_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_BUCKET1);
		RKEY(IMAGE_ZOMBIE_BUCKET2);
		RKEY(IMAGE_ZOMBIE_BUCKET3);
		RKEY(IMAGE_FASTZOMBIE_BUCKET1);
		RKEY(IMAGE_FASTZOMBIE_BUCKET2);
		RKEY(IMAGE_FASTZOMBIE_BUCKET3);
		RKEY(IMAGE_ZOMBIE_DISCO_OUTERARM_UPPER_BONE);
		RKEY(IMAGE_ZOMBIE_DOLPHINRIDER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_ELITEDOLPHINRIDER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_FOOTBALL_LEFTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_FOOTBALL_HELMET);
		RKEY(IMAGE_ZOMBIE_FOOTBALL_HELMET2);
		RKEY(IMAGE_ZOMBIE_FOOTBALL_HELMET3);
		RKEY(IMAGE_ZOMBIE_ICE_EXECUTIONER_HELMET);
		RKEY(IMAGE_ZOMBIE_ICE_EXECUTIONER_HELMET2);
		RKEY(IMAGE_ZOMBIE_ICE_EXECUTIONER_HELMET3);
		RKEY(IMAGE_ZOMBIE_PINKFOOTBALL_LEFTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_PINKFOOTBALL_HELMET);
		RKEY(IMAGE_ZOMBIE_PINKFOOTBALL_HELMET2);
		RKEY(IMAGE_ZOMBIE_PINKFOOTBALL_HELMET3);
		RKEY(IMAGE_ZOMBIE_SCREENDOOR1);
		RKEY(IMAGE_ZOMBIE_SCREENDOOR2);
		RKEY(IMAGE_ZOMBIE_SCREENDOOR3);
		RKEY(IMAGE_ZOMBIE_REINFORCED_SCREENDOOR1);
		RKEY(IMAGE_ZOMBIE_REINFORCED_SCREENDOOR2);
		RKEY(IMAGE_ZOMBIE_REINFORCED_SCREENDOOR3);
		RKEY(IMAGE_ZOMBIE_ZAMBONI_WHEEL_FLAT);
		RKEY(IMAGE_REANIM_ZOMBIE_CATAPULT_BASKETBALL);
		RKEY(IMAGE_REANIM_ZOMBIE_CATAPULT_POLE);
		RKEY(IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_WITHBALL);
		RKEY(IMAGE_REANIM_ZOMBIE_CATAPULT_SIDING);
		RKEY(IMAGE_ZOMBIE_CATAPULT_SIDING_DAMAGE);
		RKEY(IMAGE_ZOMBIE_CATAPULT_POLE_DAMAGE);
		RKEY(IMAGE_ZOMBIE_CATAPULT_POLE_DAMAGE_WITHBALL);
		RKEY(IMAGE_REANIM_ZOMBIE_ELITE_CATAPULT_SIDING);
		RKEY(IMAGE_ZOMBIE_ELITE_CATAPULT_SIDING_DAMAGE);
		RKEY(IMAGE_ZOMBIE_ELITE_CATAPULT_MANHOLE);
		RKEY(IMAGE_REANIM_ZOMBIE_ROOFMARSHAL_BODY);
		RKEY(IMAGE_REANIM_ZOMBIE_ROOFMARSHAL_HAT);
		RKEY(IMAGE_REANIM_ZOMBIE_ROOFMARSHAL_TIE);
		RKEY(IMAGE_ZOMBIE_ROOFMARSHAL_OUTERARM_UPPER2);
		RKEY(IMAGE_REANIM_ZOMBIE_FLAG1);
		RKEY(IMAGE_ZOMBIE_INSULATOR_ARMOR1);
		RKEY(IMAGE_ZOMBIE_INSULATOR_ARMOR2);
		RKEY(IMAGE_ZOMBIE_INSULATOR_ARMOR3);
		RKEY(IMAGE_ZOMBIE_ADAPTIVE_HELMET);
		RKEY(IMAGE_ZOMBIE_ADAPTIVE_BADGE);
		RKEY(IMAGE_ZOMBIE_THERMAL_GOGGLES);
		RKEY(IMAGE_ZOMBIE_THERMAL_PACK);
		RKEY(IMAGE_ZOMBIE_THERMAL_RIFLE);
		RKEY(IMAGE_ZOMBIE_AURORA_DEVICE);
		RKEY(IMAGE_ZOMBIE_AURORA_PRISM);
		RKEY(IMAGE_ZOMBIE_POLAR_CLOCK_DISK);
		RKEY(IMAGE_ZOMBIE_POLAR_PENDULUM);
		RKEY(IMAGE_ZOMBIE_HEALER_BODY);
		RKEY(IMAGE_ZOMBIE_HEALER_GEAR_IDLE);
		RKEY(IMAGE_ZOMBIE_HEALER_GEAR_AREA);
		RKEY(IMAGE_ZOMBIE_HEALER_GEAR_FOCUSED);
		RKEY(IMAGE_ZOMBIE_HEALER_GEAR_DISABLED);
		RKEY(IMAGE_ZOMBIE_GROUNDING_CONE1);
		RKEY(IMAGE_ZOMBIE_GROUNDING_CONE2);
		RKEY(IMAGE_ZOMBIE_GROUNDING_CONE3);
		RKEY(IMAGE_REANIM_ZOMBIE_GROUNDING_CONE1);
		RKEY(IMAGE_ZOMBIE_ICEWALL_ENGINEER_BODY);
		RKEY(IMAGE_ZOMBIE_ICEWALL_ENGINEER_TOOLSTRAP);
		RKEY(IMAGE_ZOMBIE_ICEWALL_ENGINEER_HAT1);
		RKEY(IMAGE_ZOMBIE_ICEWALL_ENGINEER_HAT2);
		RKEY(IMAGE_ZOMBIE_ICEWALL_ENGINEER_HAT3);
		RKEY(IMAGE_ICE_WALL);
		RKEY(IMAGE_ICE_WALL_CRACKED1);
		RKEY(IMAGE_ICE_WALL_CRACKED2);
		RKEY(IMAGE_ZOMBIE_ICECRACK_DRILL_HELMET1);
		RKEY(IMAGE_ZOMBIE_ICECRACK_DRILL_HELMET2);
		RKEY(IMAGE_ZOMBIE_ICECRACK_DRILL_HELMET3);
		RKEY(IMAGE_ZOMBIE_ICECRACK_DRILL_RIG3_SPIN0);
		RKEY(IMAGE_ICECRACKDRILLRIFT);
		RKEY(IMAGE_REANIM_ZOMBIE_WEATHER_JAMMER_PACK_READY);
		RKEY(IMAGE_REANIM_ZOMBIE_WEATHER_JAMMER_PACK_CHANNEL);
		RKEY(IMAGE_REANIM_ZOMBIE_WEATHER_JAMMER_PACK_REBOOT);
		RKEY(IMAGE_REANIM_ZOMBIE_WEATHER_JAMMER_PACK_SPENT);
		RKEY(IMAGE_REANIM_ZOMBIE_WEATHER_JAMMER_DISH);
		RKEY(IMAGE_REANIM_ZOMBIE_WEATHER_JAMMER_TERMINAL_READY);
		RKEY(IMAGE_REANIM_ZOMBIE_WEATHER_JAMMER_TERMINAL_CHANNEL);
		RKEY(IMAGE_REANIM_ZOMBIE_WEATHER_JAMMER_TERMINAL_REBOOT);
		RKEY(IMAGE_REANIM_ZOMBIE_WEATHER_JAMMER_TERMINAL_SPENT);
		RKEY(IMAGE_REANIM_ZOMBIE_HIJACKER_BODY1);
		RKEY(IMAGE_REANIM_ZOMBIE_HIJACKER_BOX);
		RKEY(IMAGE_REANIM_ZOMBIE_HIJACKER_BOX2);
		RKEY(IMAGE_REANIM_ZOMBIE_HIJACKER_HANDLE);
		RKEY(IMAGE_REANIM_ZOMBIE_HIJACKER_HEAD);
		RKEY(IMAGE_REANIM_ZOMBIE_HIJACKER_OUTERARM_LOWER);
		RKEY(IMAGE_REANIM_ZOMBIE_HIJACKER_OUTERARM_LOWER2);
		RKEY(IMAGE_ZOMBIE_JACKSON_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_LADDER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_LADDER_1);
		RKEY(IMAGE_ZOMBIE_LADDER_1_DAMAGE1);
		RKEY(IMAGE_ZOMBIE_LADDER_1_DAMAGE2);
		RKEY(IMAGE_ZOMBIE_LADDER_5);
		RKEY(IMAGE_ZOMBIE_ELITE_LADDER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_ELITE_LADDER_1);
		RKEY(IMAGE_ZOMBIE_ELITE_LADDER_1_DAMAGE1);
		RKEY(IMAGE_ZOMBIE_ELITE_LADDER_1_DAMAGE2);
		RKEY(IMAGE_ZOMBIE_ELITE_LADDER_5);
		RKEY(IMAGE_ZOMBIE_ELITE_LADDER_BODY);
		RKEY(IMAGE_ZOMBIE_ELITE_LADDER_BODY2);
		RKEY(IMAGE_ZOMBIE_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_PAPER_LEFTARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_POGO_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_POGO_STICK);
		RKEY(IMAGE_ZOMBIE_POGO_STICKHANDS2);
		RKEY(IMAGE_ZOMBIE_POGO_STICKDAMAGE2);
		RKEY(IMAGE_ZOMBIE_POGO_STICK2DAMAGE2);
		RKEY(IMAGE_ZOMBIE_ELITE_POGO_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_ELITE_POGO_STICKDAMAGE2);
		RKEY(IMAGE_ZOMBIE_ELITE_POGO_STICK2DAMAGE2);
		RKEY(IMAGE_ZOMBIE_POLEVAULTER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_SNORKLE_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_YETI_OUTERARM_UPPER2);
		RKEY(IMAGE_REANIM_ZOMBIE_DUCKYTUBE_INWATER);
		RKEY(IMAGE_REANIM_ZOMBIE_JACKBOX_OUTERARM_LOWER2);
		RKEY(IMAGE_ZOMBIE_JACKBOX_BOX);
		RKEY(IMAGE_REANIM_ZOMBIE_ELITEJACKBOX_BOX);
		RKEY(IMAGE_REANIM_ZOMBIE_ELITEJACKBOX_OUTERARM_LOWER2);
		RKEY(IMAGE_REANIM_ZOMBIE_BALLOON_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_ELITEDIGGER_OUTERARM_UPPER2);
		RKEY(IMAGE_ZOMBIE_ELITEDIGGER_HARDHAT2);
		RKEY(IMAGE_ZOMBIE_ELITEDIGGER_HARDHAT3);
		RKEY(IMAGE_ZOMBIE_ELITEDIGGER_HARDHAT);
		RKEY(IMAGE_REANIM_ZOMBIE_IMP_ARM1_BONE);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_DUCKXING);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_ZOMBIE);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_TELEPHONEPOLE);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_BODY1_2);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_BODY1_3);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_OUTERARM_LOWER2);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_FOOT2);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_HEAD2);
		RKEY(IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_HEAD_REDEYE);
		RKEY(IMAGE_ZOMBIE_GARGANTUAR_HEAD2_REDEYE);

		RKEY(IMAGE_PROJECTILECACTUS);
		RKEY(IMAGE_PROJECTILEPEA);
		RKEY(IMAGE_PROJECTILESNOWPEA);
		RKEY(IMAGE_PROJECTILETOXICPEA);
		RKEY(IMAGE_PROJECTILEAURORAPEA);
		RKEY(IMAGE_PROJECTILEAURORASNOWPEA);
		RKEY(IMAGE_PROJECTILEAURORATOXICPEA);
		RKEY(IMAGE_PROJECTILETHERMALPULSE);
		RKEY(IMAGE_PROJECTILE_STAR);
		RKEY(IMAGE_REANIM_NORTHSTARFLOWER_HEAD);
		RKEY(IMAGE_REANIM_ICEMIRRORGRASS_BODY);
		RKEY(IMAGE_REANIM_PEASHOOTER_FRONTLEAF);
		RKEY(IMAGE_REANIM_PEASHOOTER_FRONTLEAF_LEFTTIP);
		RKEY(IMAGE_REANIM_PEASHOOTER_FRONTLEAF_RIGHTTIP);
		RKEY(IMAGE_REANIM_CABBAGEPULT_CABBAGE);
		RKEY(IMAGE_REANIM_MELTSNOWPULT_SNOWCLOD);
		RKEY(IMAGE_REANIM_MELTSNOWPULT_FRONTLEAF);
		RKEY(IMAGE_REANIM_MELTSNOWPULT_FRONTLEAF_LEFTTIP);
		RKEY(IMAGE_REANIM_MELTSNOWPULT_FRONTLEAF_RIGHTTIP);
		RKEY(IMAGE_MELTSNOWPULT_SALTCRYSTAL);
		RKEY(IMAGE_REANIM_FROSTMINE_DORMANT);
		RKEY(IMAGE_REANIM_FROSTMINE_CALIBRATED);
		RKEY(IMAGE_REANIM_FROSTMINE_ARMED);
		RKEY(IMAGE_REANIM_ALARMBELLFLOWER_DIRT_BACK);
		RKEY(IMAGE_REANIM_ALARMBELLFLOWER_DIRT_FRONT);
		RKEY(IMAGE_REANIM_ALARMBELLFLOWER_STEM1);
		RKEY(IMAGE_REANIM_ALARMBELLFLOWER_STEM2);
		RKEY(IMAGE_REANIM_ALARMBELLFLOWER_PETAL);
		RKEY(IMAGE_REANIM_ALARMBELLFLOWER_HEAD);
		RKEY(IMAGE_REANIM_ALARMBELLFLOWER_HEAD2);
		RKEY(IMAGE_REANIM_ALARMBELLFLOWER_CHARM);
		RKEY(IMAGE_REANIM_FURNACECOREFLOWER_CORE);
		RKEY(IMAGE_REANIM_TORCHWOOD_FIRE1A);
		RKEY(IMAGE_COBCANNON_COB);
		RKEY(IMAGE_COBCANNON_TARGET);
		RKEY(IMAGE_COBCANNON_TARGET_SHADOW);
		RKEY(IMAGE_CORNPULT_KERNAL);
		RKEY(IMAGE_CORNPULT_BUTTER);
		RKEY(IMAGE_CORNPULT_BUTTER_SPLAT);
		RKEY(IMAGE_REANIM_MELONPULT_BLINK1);
		RKEY(IMAGE_REANIM_MELONPULT_BLINK2);
		RKEY(IMAGE_REANIM_MELONPULT_BODY);
		RKEY(IMAGE_REANIM_MELONPULT_EYEBROW);
		RKEY(IMAGE_REANIM_MELONPULT_MELON);
		RKEY(IMAGE_REANIM_MELONPULT_STALK);
		RKEY(IMAGE_REANIM_WINTERMELON_BASKET);
		RKEY(IMAGE_REANIM_WINTERMELON_BASKET_OVERLAY);
		RKEY(IMAGE_REANIM_WINTERMELON_BLINK1);
		RKEY(IMAGE_REANIM_WINTERMELON_BLINK2);
		RKEY(IMAGE_REANIM_WINTERMELON_EYEBROW);
		RKEY(IMAGE_REANIM_WINTERMELON_MELON);
		RKEY(IMAGE_REANIM_WINTERMELON_PROJECTILE);
		RKEY(IMAGE_REANIM_WINTERMELON_STALK);
		RKEY(IMAGE_UMBRELLALEAF_BLINK1);
		RKEY(IMAGE_UMBRELLALEAF_BLINK2);
		RKEY(IMAGE_REANIM_UMBRELLALEAF_BODY);
		RKEY(IMAGE_REANIM_UMBRELLALEAF_LEAF1);
		RKEY(IMAGE_REANIM_UMBRELLALEAF_LEAF2);
		RKEY(IMAGE_REANIM_UMBRELLALEAF_LEAF3);
		RKEY(IMAGE_REANIM_UMBRELLALEAF_LEAF4);
		RKEY(IMAGE_REANIM_UMBRELLALEAF_LEAF5);
		RKEY(IMAGE_REANIM_UMBRELLALEAF_LEAF6);
		RKEY(IMAGE_REANIM_UMBRELLALEAF_LEAF7);
		RKEY(IMAGE_REANIM_LISTENINGGRASS_BODY);
		RKEY(IMAGE_REANIM_LISTENINGGRASS_LEAF1);
		RKEY(IMAGE_REANIM_LISTENINGGRASS_LEAF2);
		RKEY(IMAGE_REANIM_LISTENINGGRASS_LEAF3);
		RKEY(IMAGE_REANIM_LISTENINGGRASS_LEAF4);
		RKEY(IMAGE_REANIM_LISTENINGGRASS_LEAF5);
		RKEY(IMAGE_REANIM_LISTENINGGRASS_LEAF6);
		RKEY(IMAGE_REANIM_LISTENINGGRASS_LEAF7);
		RKEY(IMAGE_MARIGOLD_BLINK1);
		RKEY(IMAGE_MARIGOLD_BLINK2);
		RKEY(IMAGE_REANIM_MARIGOLD_EYEBROW1);
		RKEY(IMAGE_REANIM_MARIGOLD_EYEBROW2);
		RKEY(IMAGE_REANIM_MARIGOLD_HEAD);
		RKEY(IMAGE_REANIM_MARIGOLD_MOUTH);
		RKEY(IMAGE_REANIM_MARIGOLD_PETALS);
		RKEY(IMAGE_REANIM_TOXICPEASHOOTER_HEAD);
		RKEY(IMAGE_REANIM_TOXICPEASHOOTER_SPROUT);
		RKEY(IMAGE_REANIM_TWINSUNFLOWER_LEAF);
		RKEY(IMAGE_REANIM_TWINSUNFLOWER_STEM1);
		RKEY(IMAGE_REANIM_TWINSUNFLOWER_STEM2);
		RKEY(IMAGE_REANIM_Z);

		// 植物图片（IMAGE_ + 大写文件名）
		RKEY(IMAGE_PEASHOOTER);
		RKEY(IMAGE_TOXICPEASHOOTER);
		RKEY(IMAGE_SUNFLOWER);
		RKEY(IMAGE_TWINSUNFLOWER);
		RKEY(IMAGE_CHERRYBOMB);
		RKEY(IMAGE_WALLNUT);
		RKEY(IMAGE_TALLNUT);
		RKEY(IMAGE_WALLNUT_BODY);
		RKEY(IMAGE_WALLNUT_CRACKED1);
		RKEY(IMAGE_WALLNUT_CRACKED2);
		RKEY(IMAGE_TALLNUT_BODY);
		RKEY(IMAGE_TALLNUT_CRACKED1);
		RKEY(IMAGE_TALLNUT_CRACKED2);
		RKEY(IMAGE_SNOWANCHORNUT);
		RKEY(IMAGE_SNOWANCHORNUT_BODY);
		RKEY(IMAGE_SNOWANCHORNUT_CRACKED1);
		RKEY(IMAGE_SNOWANCHORNUT_CRACKED2);
		RKEY(IMAGE_SNOWANCHORNUT_BRACED_BODY);
		RKEY(IMAGE_SNOWANCHORNUT_BRACED_CRACKED1);
		RKEY(IMAGE_SNOWANCHORNUT_BRACED_CRACKED2);
		RKEY(IMAGE_POTATOMINE);
		RKEY(IMAGE_POTATOMINE_MASHED);
		RKEY(IMAGE_SNOWPEASHOOTER);
		RKEY(IMAGE_CHOMPER);
		RKEY(IMAGE_REPEATER);
		RKEY(IMAGE_PUFFSHROOM);
		RKEY(IMAGE_SEASHROOM);
		RKEY(IMAGE_PLANTERN);
		RKEY(IMAGE_CACTUS);
		RKEY(IMAGE_BLOVER);
		RKEY(IMAGE_SPLITPEA);
		RKEY(IMAGE_STARFRUIT);
		RKEY(IMAGE_PUMPKIN);
		RKEY(IMAGE_PUMPKIN_FRONT);
		RKEY(IMAGE_PUMPKIN_BACK);
		RKEY(IMAGE_PUMPKIN_DAMAGE1);
		RKEY(IMAGE_PUMPKIN_DAMAGE2);
		RKEY(IMAGE_PUMPKIN_DAMAGE3);
		RKEY(IMAGE_MAGNETSHROOM);
		RKEY(IMAGE_GOLDMAGNET);
		RKEY(IMAGE_GROUNDINGSHROOM);
		RKEY(IMAGE_FLOWERPOT);
		RKEY(IMAGE_LIGHTNINGRODPOT);
		RKEY(IMAGE_CABBAGEPULT);
		RKEY(IMAGE_MELTSNOWPULT);
		RKEY(IMAGE_FROSTMINE);
		RKEY(IMAGE_ALARMBELLFLOWER);
		RKEY(IMAGE_BOUNDARYFLOWER);
		RKEY(IMAGE_DAWNLOTUS);
		RKEY(IMAGE_CARRYVINE);
		RKEY(IMAGE_CARRYVINE_BASKET);
		RKEY(IMAGE_REANIM_BOUNDARYFLOWER_MONUMENT);
		RKEY(IMAGE_REANIM_DAWNLOTUS_CROWN);
		RKEY(IMAGE_FURNACECOREFLOWER);
		RKEY(IMAGE_CORNPULT);
		RKEY(IMAGE_COBCANNON);
		RKEY(IMAGE_COFFEEBEAN);
		RKEY(IMAGE_GARLIC);
		RKEY(IMAGE_GARLIC_BODY2);
		RKEY(IMAGE_GARLIC_BODY3);
		RKEY(IMAGE_UMBRELLALEAF);
		RKEY(IMAGE_LISTENINGGRASS);
		RKEY(IMAGE_MARIGOLD);
		RKEY(IMAGE_MELONPULT);
		RKEY(IMAGE_WINTERMELON);
		RKEY(IMAGE_ZOMBIE_HEAD_GROSSOUT);
		RKEY(IMAGE_SUNSHROOM);
		RKEY(IMAGE_FUMESHROOM);
		RKEY(IMAGE_GLOOMSHROOM);
		RKEY(IMAGE_GRAVEBUSTER);
		RKEY(IMAGE_HYPNOSHROOM);
		RKEY(IMAGE_SCAREDYSHROOM);
		RKEY(IMAGE_ELITESCAREDYSHROOM);
		RKEY(IMAGE_ICESHROOM);
		RKEY(IMAGE_ICEFUMESHROOM);
		RKEY(IMAGE_ICETRAP);		// 冻结僵尸脚底冰晶（image 根目录 icetrap.png）
		RKEY(IMAGE_ICE_STATUE_SHELL); // 冰封植物前景壳；无碰撞、只由 Plant 权威状态绘制
		RKEY(IMAGE_ZOMBIE_ICE_EXECUTIONER_MAUL); // 冰像处刑者替换扶梯锤轨的独立武器
		RKEY(IMAGE_ICE);			// 冰车铺设的可平铺冰道
		RKEY(IMAGE_ICE_CAP);		// 冰道左端盖
		RKEY(IMAGE_CRATER_PART_0);		// 毁灭菇弹坑（crater.png 1行2列分份：0=白天）
		RKEY(IMAGE_CRATER_PART_1);		// 1=黑夜
		RKEY(IMAGE_CRATER_FADING_PART_0);	// 弹坑后半程消退版（同 0=白天/1=黑夜）
		RKEY(IMAGE_CRATER_FADING_PART_1);
		RKEY(IMAGE_CRATER_WATER_DAY_PART_0);	// 白天水格弹坑：0=完整、1=后半程消退
		RKEY(IMAGE_CRATER_WATER_DAY_PART_1);
		RKEY(IMAGE_CRATER_WATER_NIGHT_PART_0);	// 黑夜水格弹坑：0=完整、1=后半程消退
		RKEY(IMAGE_CRATER_WATER_NIGHT_PART_1);
		RKEY(IMAGE_CRATER_ROOF_LEFT_PART_0);	// 屋顶斜坡弹坑预留：0=完整、1=后半程消退
		RKEY(IMAGE_CRATER_ROOF_LEFT_PART_1);
		RKEY(IMAGE_CRATER_ROOF_CENTER_PART_0);	// 屋顶平面弹坑预留：0=完整、1=后半程消退
		RKEY(IMAGE_CRATER_ROOF_CENTER_PART_1);
		RKEY(IMAGE_DOOMSHROOM);
		RKEY(IMAGE_SQUASH);
		RKEY(IMAGE_THREEPEATER);
		RKEY(IMAGE_TANGLEKELP);
		RKEY(IMAGE_JALAPENO);
		RKEY(IMAGE_CALTROP);
		RKEY(IMAGE_TORCHWOOD);
		RKEY(IMAGE_GATLINGPEA);
		RKEY(IMAGE_AURORATORCHWOOD);
		RKEY(IMAGE_NORTHSTARFLOWER);
		RKEY(IMAGE_ICEMIRRORGRASS);
		RKEY(IMAGE_IMITATER);
	}

	namespace Particles
	{
		RKEY(PARTICLE_WINDSTREAK);
		RKEY(PARTICLE_HEALERPLUS);
		RKEY(PARTICLE_HEALERHALO);
		inline const std::string PARTICLE_ZOMBIE_HEAD = "PARTICLE_ZOMBIEHEAD";
		inline const std::string PARTICLE_ZOMBIE_ROOF_MARSHAL_HEAD =
			"PARTICLE_ZOMBIEROOFMARSHALHEAD";
		inline const std::string PARTICLE_ZOMBIE_HIJACKER_HEAD =
			"PARTICLE_ZOMBIEHIJACKERHEAD";
		inline const std::string PARTICLE_ZOMBIE_HIJACKER_ARM =
			"PARTICLE_ZOMBIEHIJACKERARM";
		RKEY(PARTICLE_EXPLOSIONCLOUD);
		RKEY(PARTICLE_EXPLOSIONSPUDOW);
		RKEY(PARTICLE_POTATOMINEFLASH);
		RKEY(PARTICLE_POTATOMINE_PARTICLES_PART_0);
		RKEY(PARTICLE_POTATOMINE_PARTICLES_PART_1);
		RKEY(PARTICLE_POTATOMINE_PARTICLES_PART_2);
		RKEY(PARTICLE_POTATOMINE_PARTICLES_PART_3);
		RKEY(PARTICLE_POTATOMINE_PARTICLES_PART_4);
		RKEY(PARTICLE_POTATOMINE_PARTICLES_PART_5);
		RKEY(PARTICLE_ZAMBONISMOKE);
		RKEY(PARTICLE_DIRTSMALL);
		RKEY(PARTICLE_ZOMBOSS_PARTICLES_PART_0);
		RKEY(PARTICLE_ZOMBOSS_PARTICLES_PART_1);
		RKEY(PARTICLE_ZOMBOSS_PARTICLES_PART_2);
		RKEY(PARTICLE_ZOMBOSS_PARTICLES_PART_3);
		RKEY(PARTICLE_ZOMBOSS_PARTICLES_PART_4);
		RKEY(PARTICLE_TOXICPEA_SPLATS_PART_0);
		RKEY(PARTICLE_TOXICPEA_SPLATS_PART_1);
		RKEY(PARTICLE_TOXICPEA_SPLATS_PART_2);
		RKEY(PARTICLE_TOXICPEA_SPLATS_PART_3);
		RKEY(PARTICLE_TOXICPEA_PARTICLES_PART_0);
		RKEY(PARTICLE_TOXICPEA_PARTICLES_PART_1);
		RKEY(PARTICLE_TOXICPEA_PARTICLES_PART_2);
		RKEY(PARTICLE_MELT_SNOW_SPLATS_PART_0);
		RKEY(PARTICLE_MELT_SNOW_SPLATS_PART_1);
		RKEY(PARTICLE_MELT_SNOW_SPLATS_PART_2);
		RKEY(PARTICLE_MELT_SNOW_SPLATS_PART_3);
		RKEY(PARTICLE_MELT_SNOW_PARTICLES_PART_0);
		RKEY(PARTICLE_MELT_SNOW_PARTICLES_PART_1);
		RKEY(PARTICLE_MELT_SNOW_PARTICLES_PART_2);
		RKEY(PARTICLE_SALT_CRYSTAL_SPLATS_PART_0);
		RKEY(PARTICLE_SALT_CRYSTAL_SPLATS_PART_1);
		RKEY(PARTICLE_SALT_CRYSTAL_SPLATS_PART_2);
		RKEY(PARTICLE_SALT_CRYSTAL_SPLATS_PART_3);
		RKEY(PARTICLE_SALT_CRYSTAL_PARTICLES_PART_0);
		RKEY(PARTICLE_SALT_CRYSTAL_PARTICLES_PART_1);
		RKEY(PARTICLE_SALT_CRYSTAL_PARTICLES_PART_2);
		RKEY(PARTICLE_FROSTMINESHARDS_PART_0);
		RKEY(PARTICLE_FROSTMINESHARDS_PART_1);
		RKEY(PARTICLE_FROSTMINESHARDS_PART_2);
		RKEY(PARTICLE_FROSTMINESHARDS_PART_3);
		RKEY(PARTICLE_FROSTMINEPULSE);
		RKEY(PARTICLE_ALARMBELLROWPULSE);
		RKEY(PARTICLE_AURORARIFT);
		RKEY(PARTICLE_TEMPORALGEAR);
		RKEY(PARTICLE_TEMPORALCLOCKFACE);
		RKEY(PARTICLE_TEMPORALCLOCKHOURHAND);
		RKEY(PARTICLE_TEMPORALCLOCKMINUTEHAND);
		RKEY(PARTICLE_BOUNDARYSHARD);
		RKEY(PARTICLE_DAWNFLARE);
		RKEY(PARTICLE_WATERPARTICLE_PART_0);
		RKEY(PARTICLE_WATERPARTICLE_PART_1);
		RKEY(PARTICLE_WATERPARTICLE_PART_2);
		RKEY(PARTICLE_WATERPARTICLE_PART_3);
		RKEY(PARTICLE_WATERPARTICLE_PART_4);
		RKEY(PARTICLE_WATERPARTICLE_PART_5);
		inline const std::string PARTICLE_ZOMBIE_BACKUPDANCERHEAD = "PARTICLE_ZOMBIEBACKUPDANCERHEAD";
		inline const std::string PARTICLE_ZOMBIE_BACKUPDANCERHEAD_DISCO = "PARTICLE_ZOMBIEBACKUPDANCERHEAD_DISCO";
		inline const std::string PARTICLE_ZOMBIE_BOBSLEDHEAD = "PARTICLE_ZOMBIEBOBSLEDHEAD";
		inline const std::string PARTICLE_ZOMBIE_DANCERHEAD = "PARTICLE_ZOMBIEDANCERHEAD";
		inline const std::string PARTICLE_ZOMBIE_DANCERHEAD_DISCO = "PARTICLE_ZOMBIEDANCERHEAD_DISCO";
		inline const std::string PARTICLE_ZOMBIE_DIGGERARM = "PARTICLE_ZOMBIEDIGGERARM";
		inline const std::string PARTICLE_ZOMBIE_DIGGERHEAD = "PARTICLE_ZOMBIEDIGGERHEAD";
		inline const std::string PARTICLE_ZOMBIE_SNOWBURROWARM = "PARTICLE_ZOMBIESNOWBURROWARM";
		inline const std::string PARTICLE_ZOMBIE_SNOWBURROWHEAD = "PARTICLE_ZOMBIESNOWBURROWHEAD";
		inline const std::string PARTICLE_ZOMBIE_ELITEDIGGERARM = "PARTICLE_ZOMBIEELITEDIGGERARM";
		inline const std::string PARTICLE_ZOMBIE_DOLPHINRIDERHEAD = "PARTICLE_ZOMBIEDOLPHINRIDERHEAD";
		inline const std::string PARTICLE_ZOMBIE_ELITEDOLPHINRIDERHEAD = "PARTICLE_ZOMBIEELITEDOLPHINRIDERHEAD";
		inline const std::string PARTICLE_ZOMBIE_FOOTBALLHEAD = "PARTICLE_ZOMBIEFOOTBALLHEAD";
		inline const std::string PARTICLE_ZOMBIE_IMPHEAD = "PARTICLE_ZOMBIEIMPHEAD";
		inline const std::string PARTICLE_ZOMBIE_LADDERHEAD = "PARTICLE_ZOMBIELADDERHEAD";
		inline const std::string PARTICLE_ZOMBIE_POGOHEAD = "PARTICLE_ZOMBIEPOGOHEAD";
		RKEY(PARTICLE_ZOMBIEPOGO_PART_2);
		RKEY(PARTICLE_ZOMBIEELITEPOGO_PART_2);
		inline const std::string PARTICLE_ZOMBIE_POLEVAULTERHEAD = "PARTICLE_ZOMBIEPOLEVAULTERHEAD";
		inline const std::string PARTICLE_ZOMBIE_ELITEPOLEVAULTERHEAD = "PARTICLE_ZOMBIEELITEPOLEVAULTERHEAD";
		inline const std::string PARTICLE_ZOMBIE_YETIHEAD = "PARTICLE_ZOMBIEYETIHEAD";
		RKEY(PARTICLE_ZOMBIEARM);
		RKEY(PARTICLE_ZOMBIEJACKBOXARM);
		RKEY(PARTICLE_SPROING);
		RKEY(PARTICLE_STAR40);
		RKEY(PARTICLE_MELONPULT_PARTICLES);
		RKEY(PARTICLE_WINTERMELON_PARTICLES);
		RKEY(PARTICLE_COBCANNON_POPCORN_PART_0);
		RKEY(PARTICLE_COBCANNON_POPCORN_PART_1);
		RKEY(PARTICLE_COBCANNON_POPCORN_PART_2);
		RKEY(PARTICLE_COBCANNON_POPCORN_PART_3);
		RKEY(PARTICLE_COBCANNON_POPCORN_PART_4);
		RKEY(PARTICLE_BLASTMARK);
		RKEY(PARTICLE_IMITATERCLOUDS);
		RKEY(PARTICLE_IMITATERPUFFS_PART_0);
		RKEY(PARTICLE_IMITATERPUFFS_PART_1);
		RKEY(PARTICLE_IMITATERPUFFS_PART_2);
		RKEY(PARTICLE_IMITATERPUFFS_PART_3);
		RKEY(PARTICLE_IMITATERPUFFS_PART_4);
		RKEY(PARTICLE_IMITATERPUFFS_PART_5);
		RKEY(PARTICLE_IMITATERPUFFS_PART_6);
		RKEY(PARTICLE_IMITATERPUFFS_PART_7);
	}

	namespace Fonts
	{
		inline const std::string FONT_FZJT = "./font/fzjt.ttf";
		inline const std::string FONT_FZCQ = "./font/fzcq.ttf";
		inline const std::string FONT_FZJZ = "./font/fzjz.ttf";
		inline const std::string FONT_CONTINUUMBOLD = "./font/ContinuumBold.ttf";
	}

	namespace Sounds
	{
		RKEY(SOUND_BLEEP);
		RKEY(SOUND_BUTTONCLICK);
		RKEY(SOUND_CERAMIC);
		RKEY(SOUND_CHOOSEPLANT1);
		RKEY(SOUND_CHOOSEPLANT2);
		RKEY(SOUND_GRAVEBUTTON);
		RKEY(SOUND_MAINMENU);
		RKEY(SOUND_PAUSE);
		RKEY(SOUND_SHOVEL);
		RKEY(SOUND_COLLECTSUN);
		RKEY(SOUND_CLICKFAILED);
		RKEY(SOUND_AFTERHUGEWAVE);
		RKEY(SOUND_FINALWAVE);
		RKEY(SOUND_FIRSTWAVE);
		RKEY(SOUND_LAWNMOWER);
		RKEY(SOUND_LOSTGAME);
		RKEY(SOUND_POOL_CLEANER);
		RKEY(SOUND_READYSETPLANT);
		RKEY(SOUND_WINMUSIC);
		RKEY(SOUND_CRAZYDAVESHORT1);       // 疯狂戴夫短句语音一
		RKEY(SOUND_CRAZYDAVESHORT2);       // 疯狂戴夫短句语音二
		RKEY(SOUND_CRAZYDAVESHORT3);       // 疯狂戴夫短句语音三
		RKEY(SOUND_CRAZYDAVELONG1);        // 疯狂戴夫长句语音一
		RKEY(SOUND_CRAZYDAVELONG2);        // 疯狂戴夫长句语音二
		RKEY(SOUND_CRAZYDAVELONG3);        // 疯狂戴夫长句语音三
		RKEY(SOUND_CRAZYDAVEEXTRALONG1);   // 疯狂戴夫超长句语音一
		RKEY(SOUND_CRAZYDAVEEXTRALONG2);   // 疯狂戴夫超长句语音二
		RKEY(SOUND_CRAZYDAVEEXTRALONG3);   // 疯狂戴夫超长句语音三
		RKEY(SOUND_CRAZYDAVECRAZY);        // 疯狂戴夫疯狂语气
		RKEY(SOUND_CRAZYDAVESCREAM);       // 疯狂戴夫尖叫一，保留给特殊台词
		RKEY(SOUND_CRAZYDAVESCREAM2);      // 疯狂戴夫尖叫二，保留给特殊台词
		inline const std::string SOUND_ZOMBIE_EAT = "SOUND_CHOMP";
		inline const std::string SOUND_ZOMBIE_EAT2 = "SOUND_CHOMP2";
		inline const std::string SOUND_ZOMBIE_EAT_SOFT = "SOUND_CHOMPSOFT"; // 坚果、大坚果与南瓜头的原版软啃声
		inline const std::string SOUND_ZOMBIE_FINISHEAT = "SOUND_FINISHEATING";
		RKEY(SOUND_YUCK);
		RKEY(SOUND_YUCK2);
		RKEY(SOUND_HUGEWAVE);
		RKEY(SOUND_ARM_HEAD_DROP);
		RKEY(SOUND_COOLDOWNZOMBIE);	// 寒冰豌豆首次施加减速（原版 frozen 音效入口）
		RKEY(SOUND_FROZEN);		// 寒冰菇全场冻结（原版 frozen.ogg）
		RKEY(SOUND_RAIN);			// 原版暴风雨夜循环环境音（rain.ogg）
		RKEY(SOUND_THUNDER);		// 大雨程序化闪电出现时的一次性雷声（thunder.ogg）
		inline const std::string SOUND_POLEVAULT_JUMP = "SOUND_POLEVAULT";

		RKEY(SOUND_CLICKSEED);
		RKEY(SOUND_DELETEPLANT);
		RKEY(SOUND_PLANT);
		RKEY(SOUND_PLANT_ONWATER);
		RKEY(SOUND_POTATO_MINE);
		RKEY(SOUND_SQUASH_HMM);
		RKEY(SOUND_SQUASH_HMM2);
		RKEY(SOUND_GARGANTUAR_THUMP);
		RKEY(SOUND_LOWGROAN);
		RKEY(SOUND_LOWGROAN2);
		RKEY(SOUND_SWING);
		RKEY(SOUND_IMP);
		RKEY(SOUND_IMP2);
		RKEY(SOUND_GARGANTUDEATH);
		RKEY(SOUND_ZOMBIESPLASH);
		RKEY(SOUND_FLOOP);
		inline const std::string SOUND_SHOOTER_SHOOT = "SOUND_THROW";
		inline const std::string SOUND_SHOOTER_SHOOT2 = "SOUND_THROW2";
		RKEY(SOUND_KERNELPULT);
		RKEY(SOUND_KERNELPULT2);
		RKEY(SOUND_BUTTER);
		RKEY(SOUND_MELONIMPACT);
		RKEY(SOUND_MELONIMPACT2);
		RKEY(SOUND_PUFF);
		RKEY(SOUND_CHERRYBOMB);
		RKEY(SOUND_DOOMSHROOM);				// 毁灭菇爆炸（原版 doomshroom.ogg）
		RKEY(SOUND_COBLAUNCH);				// 玉米加农炮第 78 帧发射玉米棒
		RKEY(SOUND_SHOOP);					// 玉米加农炮开始装填充能
		RKEY(SOUND_MAGNETSHROOM);			// 磁力菇锁定金属装备时的吸取声
		RKEY(SOUND_REVERSE_EXPLOSION);		// 毁灭菇引爆前吸气充能声（原版 reverse_explosion.ogg）
		RKEY(SOUND_JALAPENO);				// 火爆辣椒点燃整行（原版 jalapeno.ogg）
		RKEY(SOUND_JUICY);					// 一次性植物爆发时的汁液声（原版 juicy.ogg）
		RKEY(SOUND_ZAMBONI);				// 冰车驾驶声
		RKEY(SOUND_BASKETBALL);			// 投篮车第 46 帧发射篮球
		RKEY(SOUND_BALLOON_POP);				// 原版 TirePop Foley 使用的车辆爆胎声
		RKEY(SOUND_BALLOONINFLATE);			// 气球僵尸正式出生时的充气声
		RKEY(SOUND_PLANTGROW);				// 仙人掌发现空中目标后伸长
		RKEY(SOUND_BLOVER);					// 三叶草第 44 帧吹风结算
		RKEY(SOUND_EXPLOSION);				// 冰车爆炸声
		RKEY(SOUND_DOLPHIN_APPEARS);			// 海豚僵尸登场
		RKEY(SOUND_DOLPHIN_BEFORE_JUMPING);	// 海豚起跳前鸣叫
		RKEY(SOUND_ZOMBIE_ENTERING_WATER);	// 海豚僵尸入水
		RKEY(SOUND_PLANT_WATER);				// 海豚压水与跳跃水声
		RKEY(SOUND_BONK);					// 跳跃被高坚果等阻拦
		RKEY(SOUND_LIMBS_POP);				// 海豚僵尸断肢断头
		RKEY(SOUND_BOING);					// 小丑开盒弹簧声
		RKEY(SOUND_JACKINTHEBOX);			// 小丑行走时的循环手摇盒声
		RKEY(SOUND_HIJACKER_HUM);			// 劫持者被雷荷锁定后的独立低鸣循环声
		RKEY(SOUND_HIJACKER_EXECUTE);		// 劫持者全场处决提交时的单次紫电碎裂声
		RKEY(SOUND_JACK_SURPRISE);			// 小丑开盒惊吓声一
		RKEY(SOUND_JACK_SURPRISE2);			// 小丑开盒惊吓声二
		RKEY(SOUND_DIGGER_ZOMBIE);			// 矿工地下穿行循环声
		RKEY(SOUND_DIRT_RISE);				// 矿工破土声
		RKEY(SOUND_WAKEUP);					// 咖啡豆唤醒蘑菇与持镐矿工出土共用惊醒声
		RKEY(SOUND_COFFEE);					// 咖啡豆开始碎裂并给蘑菇提神
		RKEY(SOUND_POGO_ZOMBIE);			// 跳跳僵尸每次落地前的弹簧声
		RKEY(SOUND_LADDER_ZOMBIE);			// 扶梯僵尸成功把梯子搭到植物上
		RKEY(SOUND_GRASSSTEP);              // 蹦极僵尸开始下降时的草地踏步声
		RKEY(SOUND_BUNGEE_SCREAM);          // 蹦极僵尸下降尖叫一
		RKEY(SOUND_BUNGEE_SCREAM2);         // 蹦极僵尸下降尖叫二
		RKEY(SOUND_BUNGEE_SCREAM3);         // 蹦极僵尸下降尖叫三

		// 子弹击中僵尸
		RKEY(SOUND_SNOW_PEA_SPARKLES);
		inline const std::string SOUND_PEABULLET_HIT_BODY1 = "SOUND_SPLAT";
		inline const std::string SOUND_PEABULLET_HIT_BODY2 = "SOUND_SPLAT2";
		inline const std::string SOUND_PEABULLET_HIT_BODY3 = "SOUND_SPLAT3";
		RKEY(SOUND_HITCONE);
		RKEY(SOUND_HITCONE2);
		RKEY(SOUND_IRONHIT);
		RKEY(SOUND_IRONHIT2);
		RKEY(SOUND_FIREPEA);				// 豌豆穿过火炬树桩后的点燃声
		RKEY(SOUND_IGNITE);				// 火豌豆命中并触发溅射的燃烧声
	}

	namespace Music
	{
		RKEY(MUSIC_MAINMENU);
		RKEY(MUSIC_CHOOSEYOURSEEDS);
		RKEY(MUSIC_DAY);
		RKEY(MUSIC_FOG);
		RKEY(MUSIC_LOONBOON);
		RKEY(MUSIC_NIGHT);
		RKEY(MUSIC_POOL);
		RKEY(MUSIC_ROOF);
		RKEY(MUSIC_ZENGARDEN);
	}

	// 新增植物/僵尸/资源时，在对应 namespace 加资源键；完整新增步骤见
	// Game/Plant/GameDataManager.cpp 的 InitializeHardcodedData 顶部说明。
	// reanim 键名 ≠ 键值（值是 CamelCase 文件名），故全部显式书写，不用 RKEY。
	namespace Reanimations
	{
		inline const std::string REANIM_SUN = "Sun";
		inline const std::string REANIM_SLEEPING = "Z";
		inline const std::string REANIM_CRAZY_DAVE = "CrazyDave";

		inline const std::string REANIM_SUNFLOWER = "SunFlower";
		inline const std::string REANIM_TWINSUNFLOWER = "TwinSunflower";
		inline const std::string REANIM_PEASHOOTER = "PeaShooter";
		inline const std::string REANIM_TOXICPEASHOOTER = "ToxicPeaShooter";
		inline const std::string REANIM_CHERRYBOMB = "CherryBomb";
		inline const std::string REANIM_WALLNUT = "Wallnut";
		inline const std::string REANIM_TALLNUT = "Tallnut";
		inline const std::string REANIM_SNOWANCHORNUT = "SnowAnchorNut";
		inline const std::string REANIM_POTATOMINE = "PotatoMine";
		inline const std::string REANIM_SNOWPEASHOOTER = "SnowPeaShooter";
		inline const std::string REANIM_LILYPAD = "LilyPad";
		inline const std::string REANIM_SQUASH = "Squash";
		inline const std::string REANIM_THREEPEATER = "ThreePeater";
		inline const std::string REANIM_TANGLEKELP = "Tanglekelp";
		inline const std::string REANIM_JALAPENO = "Jalapeno";
		inline const std::string REANIM_JALAPENO_FIRE = "Fire";
		inline const std::string REANIM_CALTROP = "Caltrop";
		inline const std::string REANIM_TORCHWOOD = "Torchwood";
		inline const std::string REANIM_GATLINGPEA = "GatlingPea";
		inline const std::string REANIM_AURORATORCHWOOD = "AuroraTorchwood";
		inline const std::string REANIM_FIREPEA = "FirePea";
		inline const std::string REANIM_SEASHROOM = "SeaShroom";
		inline const std::string REANIM_PLANTERN = "Plantern";
		inline const std::string REANIM_CACTUS = "Cactus";
		inline const std::string REANIM_BLOVER = "Blover";
		inline const std::string REANIM_SPLITPEA = "SplitPea";
		inline const std::string REANIM_STARFRUIT = "Starfruit";
		inline const std::string REANIM_PUMPKIN = "Pumpkin";
		inline const std::string REANIM_MAGNETSHROOM = "Magnetshroom";
		inline const std::string REANIM_GOLDMAGNET = "GoldMagnet";
		inline const std::string REANIM_GROUNDINGSHROOM = "GroundingShroom";
		inline const std::string REANIM_FLOWERPOT = "Pot";
		inline const std::string REANIM_LIGHTNINGRODPOT = "LightningRodPot";
		inline const std::string REANIM_CABBAGEPULT = "Cabbagepult";
		inline const std::string REANIM_MELTSNOWPULT = "MeltSnowPult";
		inline const std::string REANIM_FROSTMINE = "FrostMine";
		inline const std::string REANIM_ALARMBELLFLOWER = "AlarmBellFlower";
		inline const std::string REANIM_BOUNDARYFLOWER = "BoundaryFlower";
		inline const std::string REANIM_DAWNLOTUS = "DawnLotus";
		inline const std::string REANIM_CARRYVINE = "CarryVine";
		inline const std::string REANIM_FURNACECOREFLOWER = "FurnaceCoreFlower";
		inline const std::string REANIM_LISTENINGGRASS = "ListeningGrass";
		inline const std::string REANIM_NORTHSTARFLOWER = "NorthStarFlower";
		inline const std::string REANIM_ICEMIRRORGRASS = "IceMirrorGrass";
		inline const std::string REANIM_THERMAL_SNIPER_LAUNCHER = "ThermalSniperLauncher";
		inline const std::string REANIM_KERNELPULT = "Cornpult";
		inline const std::string REANIM_COBCANNON = "CobCannon";
		inline const std::string REANIM_COFFEEBEAN = "Coffeebean";
		inline const std::string REANIM_GARLIC = "Garlic";
		inline const std::string REANIM_UMBRELLALEAF = "Umbrellaleaf";
		inline const std::string REANIM_MARIGOLD = "Marigold";
		inline const std::string REANIM_MELONPULT = "Melonpult";
		inline const std::string REANIM_WINTERMELON = "WinterMelon";
		inline const std::string REANIM_GLOOMSHROOM = "GloomShroom";
		inline const std::string REANIM_IMITATER = "Imitater";

		inline const std::string REANIM_NORMAL_ZOMBIE = "NormalZombie";
		inline const std::string REANIM_CONE_ZOMBIE = "ConeZombie";
		inline const std::string REANIM_POLEVAULTER_ZOMBIE = "PolevaulterZombie";
		inline const std::string REANIM_ELITE_POLEVAULTER_ZOMBIE = "ElitePolevaulterZombie";
		inline const std::string REANIM_BUCKET_ZOMBIE = "BucketZombie";
		inline const std::string REANIM_ZOMBIE_ELITE_JACKSON = "ZombieEliteJackson";
		inline const std::string REANIM_POOL_NORMAL_ZOMBIE = "PoolNormalZombie";
		inline const std::string REANIM_POOL_CONE_ZOMBIE = "PoolConeZombie";
		inline const std::string REANIM_POOL_BUCKET_ZOMBIE = "PoolBucketZombie";
		inline const std::string REANIM_ZAMBONI_ZOMBIE = "Zamboni";
		inline const std::string REANIM_GILDED_ZAMBONI_ZOMBIE = "GildedZamboni";
		inline const std::string REANIM_DOLPHIN_RIDER_ZOMBIE = "ZombieDolphinrider";
		inline const std::string REANIM_ELITE_DOLPHIN_RIDER_ZOMBIE = "EliteDolphinRider";
		inline const std::string REANIM_JACK_IN_THE_BOX_ZOMBIE = "ZombieJackBox";
		inline const std::string REANIM_ELITE_JACK_IN_THE_BOX_ZOMBIE = "EliteJackBox";
		inline const std::string REANIM_BALLOON_ZOMBIE = "ZombieBalloon";
		inline const std::string REANIM_DIGGER_ZOMBIE = "ZombieDigger";
		inline const std::string REANIM_SNOW_BURROW_ZOMBIE = "SnowBurrow";
		inline const std::string REANIM_ELITE_DIGGER_ZOMBIE = "EliteDigger";
		inline const std::string REANIM_POGO_ZOMBIE = "ZombiePogo";
		inline const std::string REANIM_ELITE_POGO_ZOMBIE = "ElitePogoZombie";
		inline const std::string REANIM_BUNGEE_ZOMBIE = "ZombieBungi";
		inline const std::string REANIM_LADDER_ZOMBIE = "ZombieLadder";
		inline const std::string REANIM_ELITE_LADDER_ZOMBIE = "EliteLadderZombie";
		inline const std::string REANIM_CATAPULT_ZOMBIE = "CatapultZombie";
		inline const std::string REANIM_ELITE_CATAPULT_ZOMBIE = "EliteCatapultZombie";
		inline const std::string REANIM_GARGANTUAR_ZOMBIE = "GargantuarZombie";
		inline const std::string REANIM_IMP_ZOMBIE = "ImpZombie";
		inline const std::string REANIM_ROOF_MARSHAL_ZOMBIE = "RoofMarshalZombie";
		inline const std::string REANIM_ROOF_MARSHAL_ASSAULT_FLAG = "RoofMarshalAssaultFlag";
		inline const std::string REANIM_HIJACKER_ZOMBIE = "ZombieHijacker";
		inline const std::string REANIM_GROUNDING_ZOMBIE = "GroundingZombie";
		inline const std::string REANIM_BOBSLED_TEAM_ZOMBIE = "ZombieBobsled";
		inline const std::string REANIM_ICE_CRACK_DRILL_RIG = "IceCrackDrillRig";
		inline const std::string REANIM_WEATHER_JAMMER_PACK = "WeatherJammerPack";
		inline const std::string REANIM_WEATHER_JAMMER_TERMINAL = "WeatherJammerTerminal";
		inline const std::string REANIM_DIGGER_RISING_DIRT = "DiggerRisingDirt";
		inline const std::string REANIM_DIGGER_CHARRED = "DiggerCharred";
		inline const std::string REANIM_ZOMBIE_SURPRISE = "ZombieSurprise";
		inline const std::string REANIM_ZAMBONI_CHARRED = "Zamboni_Charred";
		inline const std::string REANIM_CATAPULT_CHARRED = "Catapult_Charred";
		inline const std::string REANIM_GARGANTUAR_CHARRED = "Gargantuar_Charred";
		inline const std::string REANIM_IMP_CHARRED = "Imp_Charred";

		inline const std::string REANIM_ZOMBIE_CHARRED = "Zombie_Charred";

		inline const std::string REANIM_LAWNMOWER = "LawnMower";
		inline const std::string REANIM_POOL_CLEANER = "PoolCleaner";
		inline const std::string REANIM_ROOF_CLEANER = "RoofCleaner";
		inline const std::string REANIM_POOL_SPLASH = "Splash";
	}
}

#undef RKEY   // 不把内部宏泄漏给包含本头的翻译单元

#endif
